import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import './index.css'
import App from './App.tsx'

// Register the service worker generated by vite-plugin-pwa.
// We use 'prompt' mode (registerType: 'prompt' in vite.config.ts) so the app
// controls when to apply the update rather than reloading automatically.
// updateSW() is exposed globally so App.tsx can trigger it from the banner.
const updateSW = registerSW({
  onNeedRefresh() {
    // Dispatch a custom event that App.tsx listens to, keeping SW logic
    // out of the React tree but still driving the update banner.
    window.dispatchEvent(new CustomEvent('pwa-update-available', { detail: { updateSW } }))
  },
  onOfflineReady() {
    console.info('[PWA] App is ready for offline use.')
  },
})

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
